project_id = "mseknmncygfoaulrakpl"

[functions.generate-proposal]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.fire-trigger]
verify_jwt = false

[functions.verify-access-code]
verify_jwt = false
